### ISSUE TITLE
Glassfish

### ISSUE THREAD

**Issue by fjsorando** [ianhlavats/primefaces-starter#4]
I get the following error with glashfish:

INFO:   Running on PrimeFaces 3.5
WARNING:   EJB5184:A system exception occurred during an invocation on EJB CountryServiceImpl, method: public void com.mycompany.service.impl.CountryServiceImpl.init(javax.servlet.ServletContext) throws java.lang.Exception
WARNING:   javax.ejb.EJBException
    at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
    at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
    at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
    at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4475)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2009)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:1979)
    at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
    at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
    at $Proxy268.init(Unknown Source)

**Comment by ianhlavats** [comment]
Thanks for reporting this issue. I am busy but looking into it and will update the code as needed to run in current versions of Eclipse and Glassfish.

**Comment by ianhlavats** [comment]
This issue is now resolved. Please use the java8-javaee7-glassfish4 branch.
