### ISSUE TITLE
Having challenges compiling the sample app with JDK 1.8 + Maven 3.x

### ISSUE THREAD

**Issue by akoranne** [ianhlavats/primefaces-starter#7]
Hi Ian,
I am purchased your book. It is very descriptive and easy to understand. Thank you!
I downloaded the sample app and am having hard time compiling it. I am using JDK 1.8, Maven 3.x; trying to compile at command line. These are the errors I get.

[INFO] javac option: -proc:only
[INFO] javac option: -d
[INFO] javac option: /Users/ajaykoranne/Workspaces/sandbox/primefaces/git/temp/primefaces-starter/primefaces-webapp/target/classes
[INFO] javac option: -s
[INFO] javac option: /Users/ajaykoranne/Workspaces/sandbox/primefaces/git/temp/primefaces-starter/primefaces-webapp/src/main/java
[INFO] diagnostic Note: Hibernate JPA 2 Static-Metamodel Generator 1.0.0.Final
[INFO] diagnostic warning: Supported source version 'RELEASE_6' from annotation processor 'org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor' less than -source '1.8'
[INFO] diagnostic /Users/ajaykoranne/Workspaces/sandbox/primefaces/git/temp/primefaces-starter/primefaces-webapp/src/main/java/com/mycompany/service/impl/EventServiceImpl.java:40: error: cannot find symbol
import com.mycompany.model.City_;
                          ^
  symbol:   class City_
  location: package com.mycompany.model
[INFO] diagnostic /Users/ajaykoranne/Workspaces/sandbox/primefaces/git/temp/primefaces-starter/primefaces-webapp/src/main/java/com/mycompany/service/impl/EventServiceImpl.java:44: error: cannot find symbol
import com.mycompany.model.Event_;
                          ^
  symbol:   class Event_
  location: package com.mycompany.model
[INFO] diagnostic /Users/ajaykoranne/Workspaces/sandbox/primefaces/git/temp/primefaces-starter/primefaces-webapp/src/main/java/com/mycompany/service/impl/EventServiceImpl.java:48: error: cannot find symbol
import com.mycompany.model.Venue_;
                          ^
  symbol:   class Venue_
  location: package com.mycompany.model 

I changed the POM file to include latest versions. But still getting the same errors. 
I would appreciate any help from you.

With Regards,
--ajay

**Comment by ianhlavats** [comment]
Thanks for reporting this issue. I am busy but looking into it and will update the code as needed to run in current versions of Eclipse and Glassfish.

**Comment by tjmarkowitz** [comment]
Ian, as of 11/1/16 I am still seeing the same problem that Ajay reported above back in 2014. I've had my university class purchase a copy of your book so that I can use it as a good example of PrimeFaces usage. So, if I can't get a working copy of it very soon, we both look bad. Could you please let me know if you came up with a fix for the "RELEASE_6" problem? I will copy my current log file from GlassFish 4.1.1 and NetBeans using Java 1.8 for you to see below. I'd REALLY like the help since we are covering PF right now in my Web App Dev course.

Many thanks,

Dr. Ted Markowitz
Electrical & Computer Engineering and Computer Science
U. of New Haven
West Haven, CT
tmarkowitz@newhaven.edu

-------------------------------------------------------------------

mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/share/java/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.1.34-33-default", arch: "amd64", family: "unix"

----------------------------------------------------------------------------------

javac option: /home/ted/unh/classes/fall16/csci-6655/code-examples/primefaces-starter/primefaces-webapp-original/src/main/java
diagnostic Note: Hibernate JPA 2 Static-Metamodel Generator 1.0.0.Final
diagnostic warning: Supported source version 'RELEASE_6' from annotation processor 'org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor' less than -source '1.8'
diagnostic warning: File for type 'com.mycompany.model.ProvinceState_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.City_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.Country_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.EventAttendance_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.User_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.Venue_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.AbstractEntity_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.UserRelationship_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.Idea_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.Content_' created in the last round will not be subject to annotation processing.
diagnostic warning: File for type 'com.mycompany.model.Event_' created in the last round will not be subject to annotation processing.
An exception has occurred in the compiler (1.8.0_101). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.IllegalStateException: endPosTable already set
	at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
	at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:350)
	at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:667)
	at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1226)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.executeWithExceptionsHandled(AbstractAnnotationProcessorMojo.java:447)
	at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.java:257)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
error on execute: error during compilation
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 7.238s
Finished at: Tue Nov 01 16:00:54 EDT 2016
Final Memory: 24M/273M
------------------------------------------------------------------------
Failed to execute goal org.bsc.maven:maven-processor-plugin:2.1.1:process (process) on project primefaces-webapp: Error executing: error during compilation -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by ianhlavats** [comment]
I pushed an updated to pom.xml that fixed the Java 8 compiler errors for me. Can you guys please give it a try and let me know how it goes? Closing this ticket now.
